# Generated by Django 5.1.6 on 2025-02-11 19:43

import django.core.validators
import django.db.models.deletion
import gestion.valiladores
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10), django.core.validators.RegexValidator('^\\d{10}$', 'La cédula debe contener exactamente 10 dígitos numéricos'), gestion.valiladores.validar_cedula])),
                ('nombre', models.CharField(max_length=100, validators=[gestion.valiladores.validar_nombre])),
                ('apellido', models.CharField(max_length=100, validators=[gestion.valiladores.validar_nombre])),
                ('puesto', models.CharField(choices=[('Gerente', 'Gerente'), ('Supervisor', 'Supervisor'), ('Empleado', 'Empleado')], max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, validators=[gestion.valiladores.validar_positivo])),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10), django.core.validators.RegexValidator('^\\d{10}$', 'El teléfono debe contener exactamente 10 dígitos numéricos')])),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Tipos_Pagos',
            fields=[
                ('id_tipo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_pago', models.CharField(max_length=100, validators=[gestion.valiladores.validar_nombre])),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Pago',
                'verbose_name_plural': 'Tipos de Pago',
                'db_table': 'Tipos_Pagos',
            },
        ),
        migrations.CreateModel(
            name='Servicios_Pagos',
            fields=[
                ('id_salario', models.AutoField(primary_key=True, serialize=False, validators=[gestion.valiladores.validar_positivo])),
                ('nombre_servicio_pago', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.tipos_pagos')),
            ],
            options={
                'verbose_name': 'Servicio de Pago',
                'verbose_name_plural': 'Servicios de Pago',
                'db_table': 'Servicios_Pagos',
            },
        ),
    ]
